import type { Service } from "@/types";

export const services: Service[] = [
  {
    id: "exterior-suv",
    name: "Exterior Detailing",
    description:
      "A complete exterior wash, clay bar treatment, and wax for a brilliant shine and protection.",
    price: 160,
    tag: "SUV",
    image: "exterior-detailing-suv",
    details: [
      "100% safe wash, foam bath",
      "Deep wheel cleaning & tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shining",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
    ],
  },
  {
    id: "interior-suv",
    name: "Interior Detailing",
    description:
      "Deep cleaning of all interior surfaces, including vacuuming, shampooing, and conditioning.",
    price: 180,
    tag: "SUV",
    image: "interior-detailing-suv",
    details: [
      "Deep cleaning of door seals",
      "Thorough vacuum",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets & seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning",
      "Head unit cleaning",
    ],
  },
  {
    id: "full-suv",
    name: "Full Detailing",
    description:
      "The best of both worlds. A comprehensive interior and exterior detailing package.",
    price: 290,
    tag: "SUV",
    image: "full-detailing-suv",
    details: [
      "100% safe wash, foam bath",
      "Deep wheel cleaning",
      "Tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shine",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
      "Deep cleaning of door seals",
      "Thorough vacuum of carpets & seats",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets/seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning (inside)",
      "Head unit cleaning",
    ],
  },
  {
    id: "cerami-coating-suv",
    name: "Ceramic Coating",
    description:
      "A long-lasting ceramic coating for superior protection against scratches, UV rays, and contaminants.",
    price: "699+",
    tag: "SUV",
    image: "ceramic-coating-suv",
  },
  {
    id: "paint-protection-suv",
    name: "Paint Protection",
    description:
      "Application of a durable paint sealant to protect your vehicle from the elements and maintain its gloss.",
    price: "999+",
    tag: "SUV",
    image: "paint-protection-suv",
  },
  // Sedan services
  {
    id: "exterior-sedan",
    name: "Exterior Detailing",
    description:
      "A complete exterior wash, clay bar treatment, and wax for a brilliant shine and protection.",
    price: 160,
    tag: "Sedan",
    image: "exterior-detailing-sedan",
    details: [
      "100% safe wash, foam bath",
      "Deep wheel cleaning & tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shining",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
    ],
  },
  {
    id: "interior-sedan",
    name: "Interior Detailing",
    description:
      "Deep cleaning of all interior surfaces, including vacuuming, shampooing, and conditioning.",
    price: 160,
    tag: "Sedan",
    image: "interior-detailing-sedan",
    details: [
      "Deep cleaning of door seals",
      "Thorough vacuum",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets & seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning",
      "Head unit cleaning",
    ],
  },
  {
    id: "full-sedan",
    name: "Full Detailing",
    description:
      "The best of both worlds. A comprehensive interior and exterior detailing package.",
    price: 260,
    tag: "Sedan",
    image: "full-detailing-sedan",
    details: [
      "100% safe wash, foam bath",
      "Deep wheel cleaning",
      "Tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shine",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
      "Deep cleaning of door seals",
      "Thorough vacuum of carpets & seats",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets/seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning (inside)",
      "Head unit cleaning",
    ],
  },
  {
    id: "cerami-coating-sedan",
    name: "Ceramic Coating",
    description:
      "A long-lasting ceramic coating for superior protection against scratches, UV rays, and contaminants.",
    price: "599+",
    tag: "Sedan",
    image: "ceramic-coating-sedan",
  },
  {
    id: "paint-protection-sedan",
    name: "Paint Protection",
    description:
      "Application of a durable paint sealant to protect your vehicle from the elements and maintain its gloss.",
    price: "899+",
    tag: "Sedan",
    image: "paint-protection-sedan",
  },
  // Truck Services
  {
    id: "exterior-truck",
    name: "Exterior Detailing",
    description:
      "A complete exterior wash, clay bar treatment, and wax for a brilliant shine and protection.",
    price: 199,
    tag: "Truck",
    image: "exterior-detailing-truck",
    details: [
      "100% safe wash, foam bath",
      "Deep wheel cleaning & tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shining",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
    ],
  },
  {
    id: "interior-truck",
    name: "Interior Detailing",
    description:
      "Deep cleaning of all interior surfaces, including vacuuming, shampooing, and conditioning.",
    price: 180,
    tag: "Truck",
    image: "interior-detailing-truck",
    details: [
      "Deep cleaning of door seals",
      "Thorough vacuum",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets & seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning",
      "Head unit cleaning",
    ],
  },
  {
    id: "full-truck",
    name: "Full Detailing",
    description:
      "The best of both worlds. A comprehensive interior and exterior detailing package.",
    price: 350,
    tag: "Truck",
    image: "full-detailing-truck",
    details: [
      "100% safe wash, foam bath",
      "Deep wheel cleaning",
      "Tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shine",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
      "Deep cleaning of door seals",
      "Thorough vacuum of carpets & seats",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets/seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning (inside)",
      "Head unit cleaning",
    ],
  },
  {
    id: "cerami-coating-truck",
    name: "Ceramic Coating",
    description:
      "A long-lasting ceramic coating for superior protection against scratches, UV rays, and contaminants.",
    price: "899+",
    tag: "Truck",
    image: "ceramic-coating-truck",
  },
  {
    id: "paint-protection-truck",
    name: "Paint Protection",
    description:
      "Application of a durable paint sealant to protect your vehicle from the elements and maintain its gloss.",
    price: "1099+",
    tag: "Truck",
    image: "paint-protection-truck",
  },
  // Boat services
  {
    id: "exterior-boat",
    name: "Exterior Detailing",
    description:
      "A complete exterior wash, clay bar treatment, and wax for a brilliant shine and protection.",
    price: "5-$10 per foot",
    tag: "Boat",
    image: "exterior-detailing-boat",
    details: [
      "Rinse & foam wash",
      "Hand scrub with marine-safe soap",
      "Clean windows & brightwork",
      "Rinse & dry",
      "100% safe wash, foam bath",
      "Deep wheel cleaning & tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shining",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
    ],
  },
  {
    id: "interior-boat",
    name: "Interior Detailing",
    description:
      "Deep cleaning of all interior surfaces, including vacuuming, shampooing, and conditioning.",
    price: "6-$10 per foot",
    tag: "Boat",
    image: "interior-detailing-boat",
    details: [
      "Small boats / runabouts: $50 – $150 flat",
      "Mid-size cruisers: $150 – $300 flat",
      "Large yachts: $300 – $500+",
      "Deep cleaning of door seals",
      "Thorough vacuum",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets & seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning",
      "Head unit cleaning",
    ],
  },
  {
    id: "full-boat",
    name: "Full Detailing",
    description:
      "The best of both worlds. A comprehensive interior and exterior detailing package.",
    price: "25 – $60 per foot",
    tag: "Boat",
    image: "full-detailing-boat",
    details: [
      "Full wash, wax, polish",
      "Interior deep cleaning",
      "Windows, metal, & upholstery care",
      "100% safe wash, foam bath",
      "Deep wheel cleaning",
      "Tire shine",
      "Wheel silica/protectant",
      "Deep wheel well cleaning",
      "Wheel well silica/shine",
      "2-step paint decontamination",
      "6-month ceramic wax",
      "Trim shield (conditions & protects)",
      "Engine detail",
      "Chrome polish (if applicable)",
      "Detail finishing spray",
      "Deep cleaning of door seals",
      "Thorough vacuum of carpets & seats",
      "Steam cleaning of all plastics",
      "Steam cleaning and soaping of carpets/seats",
      "Deep leather cleaning and conditioning (if applicable)",
      "Windows cleaning (inside)",
      "Head unit cleaning",
    ],
  },
  {
    id: "ceramic-coating-boat",
    name: "Ceramic Coating",
    description:
      "A long-lasting ceramic coating for superior protection against scratches, UV rays, and contaminants.",
    price: "999+ boat size",
    tag: "Boat",
    image: "ceramic-coating-boat",
  },
  {
    id: "paint-protection-boat",
    name: "Paint Protection",
    description:
      "Application of a durable paint sealant to protect your vehicle from the elements and maintain its gloss.",
    price: "1199+ boat size" ,
    tag: "Boat",
    image: "paint-protection-boat",
  },
  // other services
];
