export const testimonials = [
    {
      quote: 'CrystalDetails transformed my car! The interior looks brand new, and the shine on the exterior is incredible. Highly recommend!',
      name: 'Emily R.',
      city: 'Seattle, WA',
      avatarUrl: 'https://picsum.photos/seed/101/48/48',
      rating: 5,
    },
    {
      quote: 'Absolutely the best car detailing experience I\'ve ever had. They really cared about my car and it shows!',
      name: 'Mike J.',
      city: 'Miami, FL',
      avatarUrl: 'https://picsum.photos/seed/102/48/48',
      rating: 4,
    },
    {
      quote: 'Quick, professional, and extremely detailed. My SUV has never looked better. I\'ll definitely CrystalDetails again!',
      name: 'Sarah K.',
      city: 'Los Angeles, CA',
      avatarUrl: 'https://picsum.photos/seed/103/48/48',
      rating: 5,
    },
    {
      quote: 'I couldn\'t believe how clean my car was. They came to my house and left my car spotless. So convenient!',
      name: 'David L.',
      city: 'New York, NY',
      avatarUrl: 'https://picsum.photos/seed/104/48/48',
      rating: 4,
    },
    {
      quote: 'Fantastic service! They were professional and friendly. They did an amazing job on my classic car. I trust them completely.',
      name: 'Jessica P.',
      city: 'Chicago, IL',
      avatarUrl: 'https://picsum.photos/seed/105/48/48',
      rating: 5,
    },
    {
      quote: 'The ceramic coating is worth every penny. My car is so easy to clean now and it always looks glossy. Great investment!',
      name: 'Chris B.',
      city: 'Houston, TX',
      avatarUrl: 'https://picsum.photos/seed/106/48/48',
      rating: 5,
    },
    {
      quote: 'My truck looks better than it did when I drove it off the lot. The attention to detail is just phenomenal.',
      name: 'Kevin S.',
      city: 'Denver, CO',
      avatarUrl: 'https://picsum.photos/seed/107/48/48',
      rating: 4,
    },
    {
      quote: 'Top-notch service from start to finish. The team was punctual and the results speak for themselves. My car is gleaming.',
      name: 'Amanda T.',
      city: 'Boston, MA',
      avatarUrl: 'https://picsum.photos/seed/108/48/48',
      rating: 5,
    },
    {
      quote: 'I was hesitant about mobile detailing, but CrystalDetails exceeded all my expectations. Flawless work.',
      name: 'Brian G.',
      city: 'Phoenix, AZ',
      avatarUrl: 'https://picsum.photos/seed/109/48/48',
      rating: 4,
    },
    {
      quote: 'They removed stains from my seats that I thought were permanent. The interior cleaning is magical.',
      name: 'Olivia H.',
      city: 'Atlanta, GA',
      avatarUrl: 'https://picsum.photos/seed/110/48/48',
      rating: 5,
    },
    {
      quote: 'The convenience of having them come to my office is a game-changer. Excellent service and a beautiful result.',
      name: 'James W.',
      city: 'Dallas, TX',
      avatarUrl: 'https://picsum.photos/seed/111/48/48',
      rating: 5,
    },
    {
      quote: 'The paint protection film application was perfect. You can\'t even tell it\'s there, but I know my car is protected.',
      name: 'Sophia M.',
      city: 'San Francisco, CA',
      avatarUrl: 'https://picsum.photos/seed/112/48/48',
      rating: 4,
    },
    {
      quote: 'Professional, courteous, and efficient. My car has never been so clean. Will be a repeat customer for sure.',
      name: 'Daniel C.',
      city: 'Philadelphia, PA',
      avatarUrl: 'https://picsum.photos/seed/113/48/48',
      rating: 5,
    },
    {
      quote: 'They are true artists when it comes to car detailing. The level of care and precision is unmatched.',
      name: 'Isabella N.',
      city: 'Las Vegas, NV',
      avatarUrl: 'https://picsum.photos/seed/114/48/48',
      rating: 4,
    },
    {
      quote: 'My car feels brand new again. I\'m so impressed with the quality of their work and their professionalism.',
      name: 'Matthew K.',
      city: 'Detroit, MI',
      avatarUrl: 'https://picsum.photos/seed/115/48/48',
      rating: 5,
    },
    {
      quote: 'Exceptional service! The team was friendly and did an incredible job on my vintage convertible. Looks show-ready!',
      name: 'Ava L.',
      city: 'San Diego, CA',
      avatarUrl: 'https://picsum.photos/seed/116/48/48',
      rating: 3,
    },
    {
      quote: 'The ceramic coating they applied is amazing. Water just beads off and the car stays cleaner for longer.',
      name: 'Ethan P.',
      city: 'Austin, TX',
      avatarUrl: 'https://picsum.photos/seed/117/48/48',
      rating: 5,
    },
    {
      quote: 'I highly recommend CrystalDetails to anyone who loves their car. You won\'t find a better detailing service.',
      name: 'Mia G.',
      city: 'Portland, OR',
      avatarUrl: 'https://picsum.photos/seed/118/48/48',
      rating: 5,
    }
  ];
  